### ISSUE TITLE
Host is down

### ISSUE THREAD

**Issue by nottix** [ScR4tCh/timebox#4]
Hi @ScR4tCh ,

I'm using Timebox to show personalized messages or custom images, but I have a problem that has always afflicted me. Every day I have to restart the Timebox at least once, as it no longer allows connections from any device (Mac, Android smartphone or Raspberry)

**Comment by ScR4tCh** [comment]
Hi, i noticed the same problem when often sending messages to the timebox.I also had some crashes when using the original "App". Maybe there is some kind of firmware issue. Perhaps keeping the connection alive might help, but to be honest, I have no clue :).

**Comment by nottix** [comment]
Hi @ScR4tCh ,

i tried to add a receive command after every send command, now i have to restart timebox about every 4-5 days.  I'll try to contact divoom ;-)

**Comment by ScR4tCh** [comment]
Well, that sounds like some sort of issue on the device side, I'd guess. Haven't played with my timebox for some time now, when I've got some spare time I'll test and push my latest changes (receiving answers and connection keep-alive are already implemented but not yet tested, because of little time).
If you can get any information from divoom, please let me know :).

**Comment by ScR4tCh** [comment]
@nottix Any news ? Otherwise I'd close this issue for now

**Comment by nottix** [comment]
No. It's an hardware issue. 

Thank you

**Comment by nottix** [comment]
No. It's an hardware issue. 

Thank you
